package presentacion.comando;


public enum IDEventos {
	
	//CLIENTE
	 EVENTO_ALTA_CLIENTE,
	 ERROR_EVENTO_ALTA_CLIENTE,
	 EVENTO_BAJA_CLIENTE,
	 ERROR_EVENTO_BAJA_CLIENTE,
	 EVENTO_CONSULTAR_UN_CLIENTE,
	 ERROR_EVENTO_CONSULTAR_UN_CLIENTE,
	 EVENTO_LISTAR_CLIENTES,
	 ERROR_EVENTO_LISTAR_CLIENTES,
	 EVENTO_MODIFICAR_CLIENTE,
	 ERROR_EVENTO_MODIFICAR_CLIENTE,
	 EVENTO_TOP_TEN_CLIENTES,
	 ERROR_EVENTO_TOP_TEN_CLIENTES, 
	
		
	//PRODUCTO 
	 EVENTO_ALTA_PRODUCTO,
	 ERROR_EVENTO_ALTA_PRODUCTO,
	 EVENTO_BAJA_PRODUCTO,
	 ERROR_EVENTO_BAJA_PRODUCTO,
	 EVENTO_CONSULTAR_UN_PRODUCTO,
	 ERROR_EVENTO_CONSULTAR_UN_PRODUCTO,
	 EVENTO_LISTAR_PRODUCTOS,
	 ERROR_EVENTO_LISTAR_PRODUCTOS,
	 EVENTO_MODIFICAR_PRODUCTO,
	 ERROR_EVENTO_MODIFICAR_PRODUCTO,
	 EVENTO_TOP_PRODUCTO,
	 ERROR_EVENTO_TOP_PRODUCTO,
	
	
	 //VENTA
	 EVENTO_ABRIR_VENTA,
	 ERROR_EVENTO_ABRIR_VENTA,
	 EVENTO_CERRAR_VENTA,
	 ERROR_EVENTO_CERRAR_VENTA,
	 EVENTO_CONSULTAR_UNA_VENTA,
	 ERROR_EVENTO_CONSULTAR_UNA_VENTA,
	 EVENTO_LISTAR_VENTAS,
	 ERROR_EVENTO_LISTAR_VENTAS,
	 EVENTO_DEVOLUCION_VENTA,
	 ERROR_EVENTO_DEVOLUCION_VENTA,
	 EVENTO_ANADIR_PRODUCTO_CARRITO,
	 ERROR_EVENTO_ANADIR_PRODUCTO_CARRITO,
	 EVENTO_ELIMINAR_PRODUCTO_CARRITO,
	 ERROR_EVENTO_ELIMINAR_PRODUCTO_CARRITO,
	 
	 
	//EMPLEADO
	 EVENTO_ALTA_EMPLEADO,
	 ERROR_EVENTO_ALTA_EMPLEADO,
	 EVENTO_BAJA_EMPLEADO,
	 ERROR_EVENTO_BAJA_EMPLEADO,
	 EVENTO_CONSULTAR_UN_EMPLEADO,
	 ERROR_EVENTO_CONSULTAR_UN_EMPLEADO,
	 EVENTO_LISTAR_EMPLEADOS,
	 ERROR_EVENTO_LISTAR_EMPLEADOS,
	 EVENTO_MODIFICAR_EMPLEADO,
	 ERROR_EVENTO_MODIFICAR_EMPLEADO,
	 EVENTO_NOMINA_EMPLEADO,
	 ERROR_EVENTO_NOMINA_EMPLEADO,
	 
	 
	//DEPARTAMENTO
	 EVENTO_ALTA_DEPARTAMENTO,
	 ERROR_EVENTO_ALTA_DEPARTAMENTO,
	 EVENTO_BAJA_DEPARTAMENTO,
	 ERROR_EVENTO_BAJA_DEPARTAMENTO,
	 EVENTO_CONSULTAR_UN_DEPARTAMENTO,
	 ERROR_EVENTO_CONSULTAR_UN_DEPARTAMENTO,
	 EVENTO_LISTAR_DEPARTAMENTOS,
	 ERROR_EVENTO_LISTAR_DEPARTAMENTOS,
	 EVENTO_MODIFICAR_DEPARTAMENTO,
	 ERROR_EVENTO_MODIFICAR_DEPARTAMENTO,
	 EVENTO_NOMINA_DEPARTAMENTO,
	 ERROR_EVENTO_NOMINA_DEPARTAMENTO,
	 EVENTO_EMPLEADOS_DEPARTAMENTO,
	 ERROR_EVENTO_EMPLEADOS_DEPARTAMENTO,
	 EVENTO_PROVEEDORES_DEPARTAMENTO,
	 ERROR_EVENTO_PROVEEDORES_DEPARTAMENTO,
	 
	 
	//PROVEEDOR
	 EVENTO_ALTA_PROVEEDOR,
	 ERROR_EVENTO_ALTA_PROVEEDOR,
	 EVENTO_BAJA_PROVEEDOR,
	 ERROR_EVENTO_BAJA_PROVEEDOR,
	 EVENTO_CONSULTAR_UN_PROVEEDOR,
	 ERROR_EVENTO_CONSULTAR_UN_PROVEEDOR,
	 EVENTO_LISTAR_PROVEEDORES,
	 ERROR_EVENTO_LISTAR_PROVEEDORES,
	 EVENTO_MODIFICAR_PROVEEDOR,
	 ERROR_EVENTO_MODIFICAR_PROVEEDOR,
	 EVENTO_ANADIR_PROVEEDOR_DEPARTAMENTO,
	 ERROR_EVENTO_ANADIR_PROVEEDOR_DEPARTAMENTO,
	 EVENTO_ELIMINAR_PROVEEDOR_DEPARTAMENTO,
	 ERROR_EVENTO_ELIMINAR_PROVEEDOR_DEPARTAMENTO
}
